### ISSUE TITLE
Tag files not loaded

### ISSUE THREAD

**Issue by alphashuro** [baysao/meteor-riotjs#3]
After upgrading to the new version my tag files are no longer loaded by riot. 
my code:
    FlowRouter.route('/', {
        action() {
            RiotLayout.render('test');
        }
    }
is creating the #riot-root div just fine and adding riot tag attribute but the tag isnt inserted. the tag does get inserted however when i create it via js and mount it manually, but i would like to take advantage of the ease of using .tag files...

**Comment by baysao** [comment]
@alphashuro just update new version. please try to update and check again.

**Comment by alphashuro** [comment]
Updated to the new version, and now getting 'riot is not defined' just before meteor exists with code 8, and i haven't referenced riot anywhere in my code :(

**Comment by alphashuro** [comment]
I just realized the files are now required to be on the client side code, even though they worked without this requirement in the older version of your package, otherwise it seems to work so far :) it would be nice if you could explicitly specify this change in your docs, thank you @baysao
