### ISSUE TITLE
Show compiler output on error

### ISSUE THREAD

**Issue by alphashuro** [baysao/meteor-riotjs#5]
The riot compiler doesn't show any output when it runs into an error in a tag file... Any idea how I can see the errors it runs into when it fails to compile tags?

**Comment by baysao** [comment]
@alphashuro today i upgrade version 2.3.1-37. Please test again for warning compiler message.

**Comment by alphashuro** [comment]
It seems you have changed the compiler to handle .jade.tag instead of .tag.jade files, but thank you for the compiler output, any posibility you could combine it with riot 2.3.11? because when I run meteor update it still says my package is out of date (also, the package doesn't update when I run meteor update baysao:riotjs)
